#!/usr/bin/env python3

#
# sxtractor
# Shellcode Extractor
#
# Created by EntySec on 2020.
# Copyright (C) 2020 by EntySec. All rights reserved.
#

import sys
import re

def help_usage():
    print("Usage: objdump -d <input_file> | sxtractor")

def main():
    shellcode = ""
    lenght = 0
    if not sys.stdin.isatty():
        try:
            while 1:
                item = sys.stdin.readline()
                if item:
                    if re.match("^[ ]*[0-9a-f]*:.*$",item):
                        item = item.split(":")[1].lstrip()
                        x = item.split("\t")
                        opcode = re.findall("[0-9a-f][0-9a-f]",x[0])
                        for i in opcode:
                            shellcode += "\\x" + i
                            lenght += 1
                else: 
                    break
        except:
            help_usage()
        print(shellcode)
        print("Shellcode Lenght: " + str(lenght))
    else:
        help_usage()
        
main()
